// components/icons.ts
import {
  Home,
  ListChecks,
  Calendar,
  Settings,
  DollarSign,
  AlertCircle,
  Baby,
  Moon,
  Sun,
  Utensils,
  Ruler,
  Pill,
  Camera,
  BedDouble,
  Syringe,
  BookOpen,
  Plus,
  X,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Edit,
  Trash,
  Save,
  Search,
  Filter,
  ArrowUp,
  ArrowDown,
  Clock,
  Thermometer,
  Stethoscope,
  Activity,
  Smile,
  Frown,
  Meh,
  Angry,
  Laugh,
  Frown as FrownIcon,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Calendar as CalendarIcon,
  AlertTriangle,
} from "lucide-react";

export const Icons = {
  dashboard: Home,
  log: ListChecks,
  calendar: Calendar,
  expenses: DollarSign,
  settings: Settings,
  alertCircle: AlertCircle,
  baby: Baby,
  moon: Moon,
  sun: Sun,
  feeding: Utensils,
  growth: Ruler,
  medication: Pill,
  photo: Camera,
  sleep: BedDouble,
  vaccination: Syringe,
  journal: BookOpen,
  add: Plus,
  close: X,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  edit: Edit,
  delete: Trash,
  save: Save,
  search: Search,
  filter: Filter,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  clock: Clock,
  calendarIcon: CalendarIcon,
  health: Stethoscope,
  temperature: Thermometer,
  activity: Activity,
  happyMood: Smile,
  sadMood: Frown,
  neutralMood: Meh,
  angryMood: Angry,
  excitedMood: Laugh,
  upsetMood: FrownIcon,
  lovingMood: Heart,
  contentMood: ThumbsUp,
  uncomfortableMood: ThumbsDown,
  fussyMood: AlertTriangle,
  mood: Smile,
};